# Generated by Django 6.0.2 on 2026-04-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Lokasi saat ini (mobile tracking)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Lokasi saat ini (mobile tracking)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Artist sedang online/menerima order'),
        ),
        migrations.AddField(
            model_name='artist',
            name='service_radius_km',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Radius layanan dalam km', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_arrival',
            field=models.IntegerField(default=0, help_text='Estimasi waktu arrival dalam menit'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_token',
            field=models.CharField(blank=True, help_text='FCM token untuk push notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Dikonfirmasi'), ('on_the_way', 'Dalam Perjalanan'), ('arrived', 'Tiba'), ('started', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('booking_new', 'Pesanan Baru'), ('booking_confirmed', 'Pesanan Dikonfirmasi'), ('booking_cancelled', 'Pesanan Dibatalkan'), ('artist_arrived', 'Seniman Tiba'), ('promo', 'Promosi')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('paid', 'Lunas'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='tedapp.booking')),
            ],
        ),
    ]
