# Generated by Django 6.0.2 on 2026-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedapp', '0002_artist_current_latitude_artist_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artist', 'Artist'), ('owner', 'Owner')], default='user', max_length=20),
        ),
    ]
