# Generated by Django 6.0.2 on 2026-05-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedapp', '0004_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tunai'), ('gopay', 'GoPay'), ('ovo', 'OVO'), ('dana', 'DANA'), ('shopeepay', 'ShopeePay'), ('transfer', 'Transfer Bank')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('paid', 'Lunas'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tunai'), ('gopay', 'GoPay'), ('ovo', 'OVO'), ('dana', 'DANA'), ('shopeepay', 'ShopeePay'), ('transfer', 'Transfer Bank')], default='cash', max_length=20),
        ),
    ]
