# Generated by Django 6.0.2 on 2026-05-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedapp', '0005_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='payment_bank_name',
            field=models.CharField(blank=True, help_text='Nama Bank', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='payment_dana',
            field=models.CharField(blank=True, help_text='Nomor DANA', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='payment_gopay',
            field=models.CharField(blank=True, help_text='Nomor GoPay', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='payment_ovo',
            field=models.CharField(blank=True, help_text='Nomor OVO', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='payment_shopeepay',
            field=models.CharField(blank=True, help_text='Nomor ShopeePay', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='payment_transfer',
            field=models.CharField(blank=True, help_text='Nomor Rekening Transfer Bank', max_length=50),
        ),
    ]
